# override only necessary data 
#
url                : http://localhost:4000
url_img            : http://localhost:4000/images/
url_assets         : http://localhost:4000/files/

google_analytics   : false
